### ISSUE TITLE
Setting environment variables.

### ISSUE THREAD

**Issue by Lerring** [planarnetwork/dtd2mysql#40]
Hi,

I'm Having trouble setting the environment variables. i have ran:

`dtd2mysql DATABASE_NAME=fares `
`dtd2mysql DATABASE_USERNAME=root`

`dtd2mysql SET DATABASE_NAME=fares `
`dtd2mysql SET DATABASE_USERNAME=root`

and the only response i get back is the default list of things to type

when i run 

`dtd2mysql --fares-clean`

i get 

`Error: Please set the DATABASE_NAME environment variable.
    at Container.get databaseConfiguration [as databaseConfiguration] (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/Container.js:111:19)
    at Container.getDatabaseConnection (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/Container.js:104:82)
    at Container.descriptor.(anonymous function) (/usr/local/lib/node_modules/dtd2mysql/node_modules/memoized-class-decorator/index.js:28:42)
    at Container.getCleanFaresCommand (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/Container.js:60:69)
    at Container.descriptor.(anonymous function) (/usr/local/lib/node_modules/dtd2mysql/node_modules/memoized-class-decorator/index.js:28:42)
    at Container.getCommand (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/Container.js:29:47)
    at Container.descriptor.(anonymous function) (/usr/local/lib/node_modules/dtd2mysql/node_modules/memoized-class-decorator/index.js:28:42)
    at Object.<anonymous> (/usr/local/lib/node_modules/dtd2mysql/dist/src/index.js:6:6)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)`

Could i get some assistance please.

**Comment by linusnorton** [comment]
Hi,

Assuming you are using Linux or a Mac, the environment variables need to be set at the start:

`DATABASE_NAME=fares SFTP_USERNAME=something dtd2mysql --get-fares`

**Comment by Lerring** [comment]
Hello,

Thanks for your reply, i guess it was simpler than i thought it would be.

Running this:

`DATABASE_USERNAME=root DATABASE_PASSWORD=XXXXX DATABASE_NAME=fares dtd2mysql --fares-clean`

Produces this:

`{ Error: connect ECONNREFUSED ::1:3306
    at PromisePool.query (/usr/local/lib/node_modules/dtd2mysql/node_modules/mysql2/promise.js:346:20)
    at CleanFaresCommand.applyRestrictionDates (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/CleanFaresCommand.js:68:51)
    at CleanFaresCommand.run (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/CleanFaresCommand.js:55:22)
    at container.getCommand.then.c (/usr/local/lib/node_modules/dtd2mysql/dist/src/index.js:7:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
  message: 'connect ECONNREFUSED ::1:3306',
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  sqlState: undefined,
  sqlMessage: undefined }

`

**Comment by linusnorton** [comment]
Is your server running on localhost?

**Comment by Lerring** [comment]
As far as i’m aware.

Is there anything special I need to set from the “Mysql” side of this? I’ve created a database named fares with the username/pwd allowing for root.

**Comment by PoNienC** [comment]
Hi,

I am running in MacOS and I have the same trouble and I have tried all the above solutions. But I still get errors:

$ DATABASE_USERNAME=root DATABASE_PASSWORD=****** DATABASE_NAME=fares dtd2mysql --fares-clean

{ Error: Unknown database 'fares'
    at PromisePool.query (/usr/local/lib/node_modules/dtd2mysql/node_modules/mysql2/promise.js:323:22)
    at CleanFaresCommand.applyRestrictionDates (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/CleanFaresCommand.js:68:51)
    at CleanFaresCommand.run (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/CleanFaresCommand.js:55:22)
    at container.getCommand.then.c (/usr/local/lib/node_modules/dtd2mysql/dist/src/index.js:7:18)
    at process._tickCallback (internal/process/next_tick.js:43:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  message: "Unknown database 'fares'",
  code: 'ER_BAD_DB_ERROR',
  errno: 1049,
  sqlState: '42000',
  sqlMessage: "Unknown database 'fares'" }

Looks like it couldn't find the database. I would appreciate any solutions. Thanks.

**Comment by linusnorton** [comment]
In this case it looks like it can connect to the server but the `fares` database doesn't exist

**Comment by PoNienC** [comment]
Hi linusnorton,
Thanks for the reply. In this case, did you mean that the fares database doesn't exist on the server or I have to create a local database in my laptop to fetch the data? Could you please tell me more specifically how can I fix this problem? I really appreciate your help.

**Comment by linusnorton** [comment]
Unless you are specifying a remote database server it will assume that there is a server running locally with a database set up called `fares`. 

I believe you need to install mysql or mariadb and then run the `CREATE DATABASE fares;` query.

**Comment by PoNienC** [comment]
Thanks for the reply.
I have successfully install Mysql and create database name in fares
However, I got error of the invalid username when I try `DATABASE_NAME=fares DATABASE_USERNAME=root DATABASE_PASSWORD=********* dtd2mysql --get-fares`

So I go back to Mysql to set up another username and password and GRANT ALL PRIVILEGES to the new user, but I still get the same result of invalid username. Do you have any idea what might cause this problem?

eduroam-int-dhcp-97-183-81:dtd2mysql pnc$ mysql -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 128
Server version: 8.0.12 Homebrew

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE DATABASE fares;
Query OK, 1 row affected (0.07 sec)

eduroam-int-dhcp-97-183-81:dtd2mysql pnc$ dtd2mysql SET DATABASE_NAME=fares

Usage: dtd2mysql [COMMAND] [FILE]
Import a DTD feed into a MySQL compatible database

  --fares [FILE]             import the fares feed 
  --fares-clean              remove old and irrelevant data
  --timetable [FILE]         import the timetable feed 
  --routeing [FILE]          import the routeing guide data
  --nfm64 [FILE]             import the nfm64 data
  --gtfs [DIR]               convert timetable data to GTFS and output txt files in DIR
  --gtfs-zip [FILE]          convert timetable data to GTFS and output zip
  --gtfs-import [DIR]        import the GTFS files in the DIR to a MySQL database
  --download-fares [DIR]     download latest fares refresh from DTD
  --download-timetable [DIR] download latest timetable refresh from DTD
  --download-routeing [DIR]  download latest routeing refresh from DTD
  --nfm64 [DIR]              download nfm64 data
  --get-fares [DIR]          download and process latest fares refresh from DTD
  --get-timetable [DIR]      download and process latest timetable refresh from DTD
  --get-routeing [DIR]       download and process latest routeing refresh from DTD
  --get-nfm64 [DIR]          download and process latest nfm64 file
  
The following environment properties are expected to be set:
  
  DATABASE_USERNAME          mysql username (defaults to root)
  DATABASE_PASSWORD          mysql password (defaults to none)
  DATABASE_NAME              mysql database name
  DATABASE_HOSTNAME          mysql database host (defaults to localhost)
  
The --get-* and --download-* commands require SFTP environment properties:

  SFTP_USERNAME              SFTP username
  SFTP_PASSWORD              SFTP password
  SFTP_HOSTNAME              SFTP hostname (defaults to dtd.atocrsp.org)

eduroam-int-dhcp-97-183-81:dtd2mysql pnc$ DATABASE_NAME=fares DATABASE_USERNAME=root DATABASE_PASSWORD=********* dtd2mysql --get-fares
Error: Invalid username
    at Client.connect (/usr/local/lib/node_modules/dtd2mysql/node_modules/ssh2/lib/client.js:183:11)
    at Promise (/usr/local/lib/node_modules/dtd2mysql/dist/src/sftp/PromiseSFTP.js:29:20)
    at new Promise (<anonymous>)
    at Function.connect (/usr/local/lib/node_modules/dtd2mysql/dist/src/sftp/PromiseSFTP.js:18:16)
    at Container.getSFTP (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/Container.js:90:42)
    at Container.descriptor.(anonymous function) (/usr/local/lib/node_modules/dtd2mysql/node_modules/memoized-class-decorator/index.js:28:42)
    at Container.getDownloadCommand (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/Container.js:78:101)
    at process._tickCallback (internal/process/next_tick.js:43:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:342:17)

**Comment by linusnorton** [comment]
Although it's not clear from the error message, it is failing to connect to the SFTP server.

You will need to set your DTD credentials with `SFTP_USERNAME` and `SFTP_PASSWORD`.

**Comment by Lerring** [comment]
I'll have another look at attempting this when i get the time, could be i was missing SFTP Usernames / Passwords also

**Comment by PoNienC** [comment]
Thank you for the replies, I also found that to `--get` ot `--download` require SFTP_USERNAME and SFTP_PASSWORD. May I ask how can I get/set SFTP username and password?

**Comment by linusnorton** [comment]
Sign up to http://data.atoc.org/

**Comment by PoNienC** [comment]
I have no problem to use my username and password to login the above webpage and download the data (as the image). However, I still got error. Any idea how it happends? 

eduroam-int-dhcp-97-183-81:dtd2mysql pnc$ DATABASE_NAME=fares SFTP_USERNAME=PNCHEN SFTP_PASSWORD=********* dtd2mysql --get-fares
{ Error: All configured authentication methods failed
    at tryNextAuth (/usr/local/lib/node_modules/dtd2mysql/node_modules/ssh2/lib/client.js:392:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/usr/local/lib/node_modules/dtd2mysql/node_modules/ssh2/lib/client.js:599:5)
    at SSH2Stream.emit (events.js:189:13)
    at parsePacket (/usr/local/lib/node_modules/dtd2mysql/node_modules/ssh2-streams/lib/ssh.js:3930:10)
    at SSH2Stream._transform (/usr/local/lib/node_modules/dtd2mysql/node_modules/ssh2-streams/lib/ssh.js:671:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/usr/local/lib/node_modules/dtd2mysql/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5) level: 'client-authentication' }

<img width="963" alt="screenshot 2019-01-04 at 14 16 36" src="https://user-images.githubusercontent.com/43548143/50692368-7e4b1a00-102b-11e9-99ea-8b273e627400.png">

**Comment by PoNienC** [comment]
I am not sure if this setting of SFTP server is correct? It looks like the port or something else is incorrect. Could you please advice me how to alter it? Or any other issues I have to solve?

eduroam-int-dhcp-97-183-81:dtd2mysql pnc$` DATABASE_NAME=fares SFTP_USERNAME=PNCHEN SFTP_PASSWORD=********* SFTP_HOSTNAME=dtd_hostname dtd2mysql --get-fares`
{ Error: getaddrinfo ENOTFOUND dtd_hostname dtd_hostname:22
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'dtd_hostname',
  host: 'dtd_hostname',
  port: 22,
  level: 'client-socket' }

**Comment by linusnorton** [comment]
It looks like you're setting `SFTP_HOSTNAME` to `dtd_hostname` - it needs to be a valid hostname. I can't remember what the data.atoc.org SFTP server host name is.
