### ISSUE TITLE
Data too long for log filename

### ISSUE THREAD

**Issue by timhowgego** [planarnetwork/dtd2mysql#56]
Fatal error when running --timetable with a bespoke filename that is greater than 12 characters long. Suggest truncating the supplied filename to match the table definition.

  ...
  Finished processing ttisf893.mca
  Error: Data too long for column 'filename' at row 1
      at PromisePool.query (...mysql2\promise.js:340:22)
      at ImportFeedCommand.updateLastFile (...dtd2mysql\dist\src\cli\ImportFeedCommand.js:105:24)
      at ImportFeedCommand.doImport (...dtd2mysql\dist\src\cli\ImportFeedCommand.js:67:20)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async ImportFeedCommand.run (...dtd2mysql\dist\src\cli\ImportFeedCommand.js:38:13) {
    code: 'ER_DATA_TOO_LONG',
    errno: 1406,
    sqlState: '22001',
    sqlMessage: "Data too long for column 'filename' at row 1"
  }

**Comment by linusnorton** [comment]
I have just released 6.3.26 which should fix this but you will need to drop you log table so it gets created again. Let me know if you have any issues
