### ISSUE TITLE
Invalid or unsupported zip format

### ISSUE THREAD

**Issue by esseswann** [planarnetwork/dtd2mysql#63]
There is an error happening with parsing today's fares which seems to be related to https://github.com/cthackers/adm-zip/issues/268
```
Extracting /tmp/fares.zip to /tmp/dtd/fares/
Error: Invalid or unsupported zip format. No END header found
    at readMainHeader (/usr/local/lib/node_modules/dtd2mysql/node_modules/adm-zip/zipFile.js:107:10)
    at new module.exports (/usr/local/lib/node_modules/dtd2mysql/node_modules/adm-zip/zipFile.js:19:3)
    at new module.exports (/usr/local/lib/node_modules/dtd2mysql/node_modules/adm-zip/adm-zip.js:20:11)
    at ImportFeedCommand.doImport (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/ImportFeedCommand.js:52:9)
    at ImportFeedCommand.run (/usr/local/lib/node_modules/dtd2mysql/dist/src/cli/ImportFeedCommand.js:39:24)
    at container.getCommand.then.c (/usr/local/lib/node_modules/dtd2mysql/dist/src/index.js:7:18)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
    at internal/main/run_main_module.js:21:11
 ```

Version 6.4.2

**Comment by linusnorton** [comment]
Which fares file are you using? Daily, or weekly? And is it the TTIS version or DTD?

**Comment by esseswann** [comment]
Full from https://opendata.nationalrail.co.uk/api/staticfeeds/2.0/fares

**Comment by esseswann** [comment]
[Here](https://drive.google.com/drive/folders/1Bsqd_d8uLQ7fPMeNVcFbQrcJxKKZlLKF) are the files in case NRE updated them on their side

**Comment by linusnorton** [comment]
I can't open the zip either. Might have to wait until the next one is released to see if they've fixed it

**Comment by esseswann** [comment]
We were able to repair the archive using WinRar 6.02. I wonder if any JS package supports such functionality

**Comment by esseswann** [comment]
Seems to be fixed on the NRE side
